name: Minimal Android CI Workflow

on:
  - push #:
    #branches:
    #  - master
    #paths:
    #  - 'app/version.properties'
  - workflow_dispatch

jobs:
  apk:
    name: Generate APK
    uses: ./.github/workflows/build_general.yml
    with:
      #BUILD-VARIANT: release
      ENV-NAME: test
    secrets: inherit
